asp_capacity = "1"
external_hostname = "probate.aat.platform.hmcts.net"
external_cert_name = "star-aat"
external_cert_vault_uri = "https://infra-vault-nonprod.vault.azure.net/"
external_hostname_gateway = "service-probate.aat.platform.hmcts.net"
external_hostname_www = "probate.aat.platform.hmcts.net"
external_hostname_www_caveats = "probate-caveats.aat.platform.hmcts.net"
