asp_capacity = "1"
external_hostname = "rpx.aat.platform.hmcts.net"
external_cert_name = "star-aat"
external_cert_vault_uri = "https://infra-vault-nonprod.vault.azure.net/"
external_hostname_gateway = "service-rpx.aat.platform.hmcts.net"
external_hostname_www = "rpx.aat.platform.hmcts.net"
external_hostname_www_caveats = "rpx-caveats.aat.platform.hmcts.net"
