asp_capacity = "1"
external_hostname = "probate.demo.platform.hmcts.net"
external_cert_name = "star-demo"
external_cert_vault_uri = "https://infra-vault-nonprod.vault.azure.net/"
external_hostname_gateway = "gateway-probate.demo.platform.hmcts.net"
external_hostname_www = "probate.demo.platform.hmcts.net"
external_hostname_www_caveats = "probate-caveats.demo.platform.hmcts.net"