external_hostname = "xui.service.gov.uk"
external_cert_name = "xui-service-gov-uk"
external_cert_vault_uri = "https://infra-vault-prod.vault.azure.net/"
external_hostname_gateway = "www.xui.service.gov.uk"
external_hostname_www = "www.xui.platform.hmcts.net"
