asp_capacity = "1"
external_hostname = "rpx.sandbox.platform.hmcts.net"
external_cert_name = "STAR-sandbox-platform-hmcts-net"
external_cert_vault_uri = "https://infra-vault-sandbox.vault.azure.net/"
external_hostname_gateway = "gateway-rpx.sandbox.platform.hmcts.net"
external_hostname_www = "www-rpx.sandbox.platform.hmcts.net"