asp_capacity = "1"
external_hostname = "probate.sandbox.platform.hmcts.net"
external_cert_name = "STAR-sandbox-platform-hmcts-net"
external_cert_vault_uri = "https://infra-vault-sandbox.vault.azure.net/"
external_hostname_gateway = "gateway-probate.sandbox.platform.hmcts.net"
external_hostname_www = "www-probate.sandbox.platform.hmcts.net"
external_hostname_www_caveats = "probate-caveats.sandbox.platform.hmcts.net"