asp_capacity = "1"
external_hostname = "rpx.sprod.platform.hmcts.net"
external_cert_name = "STAR-sprod-platform-hmcts-net"
external_cert_vault_uri = "https://infra-vault-sandbox.vault.azure.net/"
external_hostname_gateway = "service-rpx.sprod.platform.hmcts.net"
external_hostname_www = "www-rpx.sprod.platform.hmcts.net"
external_hostname_www_caveats = "rpx-caveats.sprod.platform.hmcts.net"